version: 2

project_name: kedify-analyzer

builds:
  - id: kedify-analyzer
    main: ./cmd/kedify-analyzer
    binary: kedify-analyzer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - ids:
      - kedify-analyzer
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

release:
  make_latest: true
  prerelease: auto

changelog:
  use: git

snapshot:
  version_template: "{{ .Version }}-next"
