name: PR checks

on:
  pull_request_target:
    branches: [main]

jobs:
  build-and-test:
    uses: kedify/github-meta/.github/workflows/go-pr-check.yaml@main
    with:
      continue_on_error: false
      skip_private_key_setup: true
